<a href="https://colab.research.google.com/github/thamirisbalbi/computerVisionCourse/blob/main/numpyBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [58]:
import numpy as np

np.set_printoptions(legacy='1.25')

In [ ]:
#Creating arrays

In [3]:
mylist = [1,2,3]

In [4]:
type(mylist)

list

In [6]:
myarray = np.array(mylist)

In [7]:
myarray

array([1, 2, 3])

In [8]:
type(myarray)

numpy.ndarray

In [12]:
np.arange(0,10,2) #create array of integers

array([0, 2, 4, 6, 8])

In [14]:
np.zeros(shape=(10,5)) #np.zeros create floats

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones(shape=(2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
#Operations with arrays:

In [23]:
np.random.seed(101)
arr = np.random.randint(0,100,10)

In [24]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [25]:
arr2 = np.random.randint(0,100,10)

In [28]:
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [59]:
arr.max()

95

In [55]:
arr.argmax() #index of max value

np.int64(0)

In [54]:
arr.min()

np.int64(9)

In [36]:
arr.argmin()

np.int64(7)

In [60]:
arr.mean()

60.8

In [40]:
arr.shape

(10,)

In [43]:
arr.reshape((2,5))

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [44]:
#Indexing:

In [46]:
mat = np.arange(0,100).reshape(10,10)

In [48]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [50]:
mat.shape

(10, 10)

In [51]:
row = 0
col = 1

In [52]:
mat[row,col]

np.int64(1)

In [61]:
row = 4
col = 6

In [62]:
mat[row,col]

46

In [63]:
mat[:,1]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [65]:
mat[:,1].shape

(10,)

In [66]:
mat[:,1].reshape(10,1)

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [67]:
mat[2,:]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [68]:
mat[0:3,0:4] #slice

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [69]:
mat[0:3,0:4] = 0

In [70]:
mynewmat = mat.copy()

In [71]:
mynewmat[0:6,:] = 999

In [72]:
mynewmat

array([[999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])